### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by CrimsonGlory** [kjd/idna#84] opened 2020-06-16 13:57 UTC
I'm sorry I can't provide the input (I don't have it on the logs). Still, here is a stracktrace:

```
Traceback (most recent call last):
  File "/myapp/src/my_script.py", line 15, in host_is_a_valid_domain
    idna_test = idna.decode(host)
  File "/usr/local/lib/python2.7/site-packages/idna/core.py", line 391, in decode
    s = ulabel(label)
  File "/usr/local/lib/python2.7/site-packages/idna/core.py", line 303, in ulabel
    if label.decode('ascii')[-1] == '-':
IndexError: string index out of range
```

I' have added more logging so I can have the host variable next time.

```
# pip list | grep idna
idna                          2.9
```

(I have thrown literally tens of millions of inputs at idna.decode, and this is the first time I see an IndexError. so the priority of this is low)

**Comment by CrimsonGlory** [comment] 2020-06-27 00:22
it seems the variable was: ```xn--```, but since it raises a proper exception (IDNAError('Empty Label')) on python 3, and only fails on 2.7 (and 2.7 is out of support), feel free close this issue.

**Comment by CrimsonGlory** [comment] 2020-06-27 00:32
```
>>> import idna
>>> idna.decode('xn--')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/idna/core.py", line 391, in decode
    s = ulabel(label)
  File "/usr/local/lib/python3.6/dist-packages/idna/core.py", line 303, in ulabel
    if label.decode('ascii')[-1] == '-':
IndexError: string index out of range
```

```
~$ pip list | grep idna
idna                          2.9   
```

this started happening in 2.9
2.8 seems to work fine (it raises ```IDNAError('Empty Label')```)

**Comment by kjd** [comment] 2020-06-27 23:21
This appears to be a duplicate of issue #82 which is fixed for the next release.

**Closed by kjd** 2020-06-27 23:21 UTC
